name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: asklawyers
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Register new task definition
        id: task-def
        run: |
          # Describe the current task definition and save it to a file
          aws ecs describe-task-definition --task-definition asklawyers-fargate-tasks | jq '.taskDefinition' > asklawyers-fargate-tasks.json

          # Update the image in the task definition
          jq '.containerDefinitions[0].image = "'${{ steps.login-ecr.outputs.registry }}/asklawyers:${{ github.sha }}'"' asklawyers-fargate-tasks.json > task-def-new.json

          # Add the secret to the task definition
          jq '.containerDefinitions[0].secrets = [{"name": "ASKLAWYER_OPENAI_API_KEY", "valueFrom": "arn:aws:secretsmanager:us-east-1:123456789012:secret:ASKLAWYER_OPENAI_API_KEY"}]' task-def-new.json > task-def-final.json

          # Register the new task definition
          aws ecs register-task-definition --cli-input-json file://task-def-final.json

      - name: Deploy to ECS service
        run: |
          # Get the new task definition ARN
          TASK_DEFINITION_ARN=$(jq -r '.taskDefinitionArn' task-def-final.json)
          
          # Update the ECS service with the new task definition
          aws ecs update-service --cluster aws-ecs-demo-alex-cluster --service aws-ecs-demo-alex-service --task-definition $TASK_DEFINITION_ARN
